import { describe, expect, it } from "vitest";

import { generatePostgreSQLSchema, PostgreSQLGeneratorError } from "./postgresql-generator.js";

describe("PostgreSQL generator", () => {
  const schema = {
    name: "application",
    version: "1",
    tables: [
      {
        id: "posts",
        name: "posts",
        columns: [
          { name: "id", type: "uuid" as const, primaryKey: true, nullable: false },
          { name: "title", type: "string" as const, nullable: false, indexed: true },
        ],
        constraints: [
          {
            name: "posts_title_check",
            type: "check" as const,
            expression: "length(title) > 0",
          },
        ],
      },
      {
        id: "users",
        name: "users",
        columns: [{ name: "id", type: "uuid" as const, primaryKey: true }],
        indexes: [{ name: "users_id_idx", columns: ["id"], unique: true }],
      },
    ],
  };

  it("generates deterministic PostgreSQL SQL", () => {
    const first = generatePostgreSQLSchema(schema);
    const second = generatePostgreSQLSchema({ ...schema, tables: [...schema.tables].reverse() });

    expect(first).toEqual(second);
    expect(first.path).toBe("database/schema.sql");
    expect(first.content).toContain('CREATE TABLE "posts"');
    expect(first.content).toContain('"id" UUID PRIMARY KEY');
    expect(first.content).toContain('CREATE INDEX "posts_title_idx" ON "posts" ("title");');
    expect(first.content).toContain('CREATE UNIQUE INDEX "users_id_idx" ON "users" ("id");');
  });

  it("maps defaults, generated columns, constraints, and escaped identifiers", () => {
    const artifact = generatePostgreSQLSchema({
      name: "app",
      version: "1",
      tables: [
        {
          id: "items",
          name: 'items"table',
          columns: [
            { name: "id", type: "integer", generated: true },
            { name: "active", type: "boolean", defaultValue: true, nullable: false },
          ],
          constraints: [{ name: "items_pk", type: "primary-key", columns: ["id"] }],
        },
      ],
    });

    expect(artifact.content).toContain('"items""table"');
    expect(artifact.content).toContain("GENERATED BY DEFAULT AS IDENTITY");
    expect(artifact.content).toContain("DEFAULT TRUE NOT NULL");
  });

  it("rejects foreign keys with unknown references", () => {
    expect(() =>
      generatePostgreSQLSchema({
        name: "app",
        version: "1",
        tables: [
          {
            id: "posts",
            name: "posts",
            columns: [{ name: "user_id", type: "uuid" }],
            constraints: [
              {
                name: "posts_user_fk",
                type: "foreign-key",
                columns: ["user_id"],
                referencedTable: "missing_users",
                referencedColumns: ["id"],
              },
            ],
          },
        ],
      }),
    ).toThrow(PostgreSQLGeneratorError);
  });

  it("generates composite and unique indexes with stable names", () => {
    const artifact = generatePostgreSQLSchema({
      name: "app",
      version: "1",
      tables: [
        {
          id: "memberships",
          name: "memberships",
          columns: [
            { name: "organization_id", type: "uuid" },
            { name: "user_id", type: "uuid" },
          ],
          indexes: [
            {
              name: "memberships_organization_user_uniq",
              columns: ["organization_id", "user_id"],
              unique: true,
            },
          ],
        },
      ],
    });

    expect(artifact.content).toContain(
      'CREATE UNIQUE INDEX "memberships_organization_user_uniq" ON "memberships" ("organization_id", "user_id");',
    );
  });

  it("renders supported PostgreSQL constraints", () => {
    const artifact = generatePostgreSQLSchema({
      name: "app",
      version: "1",
      tables: [
        {
          id: "users",
          name: "users",
          columns: [{ name: "id", type: "uuid" }],
        },
        {
          id: "posts",
          name: "posts",
          columns: [
            { name: "id", type: "uuid", primaryKey: true },
            { name: "user_id", type: "uuid", nullable: false },
          ],
          constraints: [
            {
              name: "posts_user_fk",
              type: "foreign-key",
              columns: ["user_id"],
              referencedTable: "users",
              referencedColumns: ["id"],
              onDelete: "cascade",
            },
            { name: "posts_user_unique", type: "unique", columns: ["user_id"] },
            { name: "posts_id_check", type: "check", expression: "length(user_id::text) > 0" },
          ],
        },
      ],
    });

    expect(artifact.content).toContain('"user_id" UUID NOT NULL');
    expect(artifact.content).toContain(
      'CONSTRAINT "posts_user_fk" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE',
    );
    expect(artifact.content).toContain('CONSTRAINT "posts_user_unique" UNIQUE ("user_id")');
    expect(artifact.content).toContain(
      'CONSTRAINT "posts_id_check" CHECK (length(user_id::text) > 0)',
    );
  });
});
