import type {
  DatabaseColumnDefinition,
  DatabaseConstraintDefinition,
  DatabaseForeignKeyConstraint,
  DatabaseSchemaDefinition,
  DatabaseTableDefinition,
} from "@mavibase/core";
import { createDatabaseIndexName } from "@mavibase/core";

import type { GeneratedFile } from "./index.js";

export interface PostgreSQLValidationIssue {
  path: string;
  message: string;
}

export class PostgreSQLGeneratorError extends Error {
  readonly code = "MAVIBASE_POSTGRESQL_GENERATOR_ERROR";
  readonly issues: readonly PostgreSQLValidationIssue[];

  constructor(issues: readonly PostgreSQLValidationIssue[]) {
    super(
      `Unable to generate PostgreSQL schema: ${issues.map((issue) => issue.message).join(" ")}`,
    );
    this.name = "PostgreSQLGeneratorError";
    this.issues = issues;
  }
}

const typeMap: Readonly<Record<DatabaseColumnDefinition["type"], string>> = {
  string: "TEXT",
  integer: "INTEGER",
  float: "DOUBLE PRECISION",
  decimal: "NUMERIC",
  boolean: "BOOLEAN",
  uuid: "UUID",
  datetime: "TIMESTAMPTZ",
  json: "JSONB",
};

export function quotePostgreSQLIdentifier(value: string): string {
  return `"${value.replaceAll('"', '""')}"`;
}

function quoteLiteral(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function defaultValue(value: unknown, type: DatabaseColumnDefinition["type"]): string {
  if (value === null) return "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (typeof value === "number" && Number.isFinite(value)) return String(value);
  if (typeof value === "string") return quoteLiteral(value);
  if (type === "json") return `${quoteLiteral(JSON.stringify(value))}::JSONB`;
  return quoteLiteral(JSON.stringify(value));
}

export function renderPostgreSQLColumn(column: DatabaseColumnDefinition): string {
  const parts = [quotePostgreSQLIdentifier(column.name), typeMap[column.type]];
  if (column.generated && column.type === "integer") {
    parts.push("GENERATED BY DEFAULT AS IDENTITY");
  }
  if (column.defaultValue !== undefined) {
    parts.push(`DEFAULT ${defaultValue(column.defaultValue, column.type)}`);
  }
  if (column.nullable === false) parts.push("NOT NULL");
  if (column.primaryKey) parts.push("PRIMARY KEY");
  if (column.unique) parts.push("UNIQUE");
  return parts.join(" ");
}

export function renderPostgreSQLConstraint(constraint: DatabaseConstraintDefinition): string {
  const name = `CONSTRAINT ${quotePostgreSQLIdentifier(constraint.name)}`;
  if (constraint.type === "check") {
    return `${name} CHECK (${constraint.expression})`;
  }
  const columns = constraint.columns.map(quotePostgreSQLIdentifier).join(", ");
  if (constraint.type === "primary-key") return `${name} PRIMARY KEY (${columns})`;
  if (constraint.type === "unique") return `${name} UNIQUE (${columns})`;

  const foreignKey = constraint as DatabaseForeignKeyConstraint;
  const actions = [
    foreignKey.onDelete ? `ON DELETE ${foreignKey.onDelete.replace("-", " ").toUpperCase()}` : "",
    foreignKey.onUpdate ? `ON UPDATE ${foreignKey.onUpdate.replace("-", " ").toUpperCase()}` : "",
  ].filter(Boolean);
  return `${name} FOREIGN KEY (${columns}) REFERENCES ${quotePostgreSQLIdentifier(foreignKey.referencedTable)} (${foreignKey.referencedColumns.map(quotePostgreSQLIdentifier).join(", ")})${actions.length > 0 ? ` ${actions.join(" ")}` : ""}`;
}

function validateReferences(schema: DatabaseSchemaDefinition): PostgreSQLValidationIssue[] {
  const issues: PostgreSQLValidationIssue[] = [];
  const tables = new Map(schema.tables.map((table) => [table.name, table]));

  for (const [tableIndex, table] of schema.tables.entries()) {
    const columns = new Set(table.columns.map((column) => column.name));
    for (const [constraintIndex, constraint] of (table.constraints ?? []).entries()) {
      if (constraint.type !== "foreign-key") continue;
      const referencedTable = tables.get(constraint.referencedTable);
      if (!referencedTable) {
        issues.push({
          path: `tables[${tableIndex}].constraints[${constraintIndex}].referencedTable`,
          message: `Foreign key references unknown table: "${constraint.referencedTable}".`,
        });
        continue;
      }
      if (constraint.columns.some((column) => !columns.has(column))) {
        issues.push({
          path: `tables[${tableIndex}].constraints[${constraintIndex}].columns`,
          message: `Foreign key on table "${table.name}" references an unknown local column.`,
        });
      }
      const referencedColumns = new Set(referencedTable.columns.map((column) => column.name));
      if (constraint.referencedColumns.some((column) => !referencedColumns.has(column))) {
        issues.push({
          path: `tables[${tableIndex}].constraints[${constraintIndex}].referencedColumns`,
          message: `Foreign key references an unknown column on table "${constraint.referencedTable}".`,
        });
      }
      if (constraint.columns.length !== constraint.referencedColumns.length) {
        issues.push({
          path: `tables[${tableIndex}].constraints[${constraintIndex}]`,
          message: "Foreign key local and referenced column counts must match.",
        });
      }
    }
  }
  return issues;
}

function indexedColumns(
  table: DatabaseTableDefinition,
): { name: string; columns: readonly string[]; unique?: boolean }[] {
  const explicit = [...(table.indexes ?? [])];
  const explicitColumns = new Set(explicit.map((index) => index.columns.join("\u0000")));
  const generated = table.columns
    .filter((column) => column.indexed && !explicitColumns.has(column.name))
    .map((column) => ({
      name: createDatabaseIndexName(table.name, [column.name]),
      columns: [column.name],
    }));
  return [...explicit, ...generated].sort((left, right) => left.name.localeCompare(right.name));
}

export function renderPostgreSQLTable(table: DatabaseTableDefinition): string {
  const lines = table.columns.map(renderPostgreSQLColumn);
  for (const constraint of table.constraints ?? [])
    lines.push(renderPostgreSQLConstraint(constraint));
  return `CREATE TABLE ${quotePostgreSQLIdentifier(table.name)} (\n  ${lines.join(",\n  ")}\n);`;
}

export function validatePostgreSQLSchema(
  schema: DatabaseSchemaDefinition,
): PostgreSQLValidationIssue[] {
  return validateReferences(schema);
}

export function generatePostgreSQLSchema(schema: DatabaseSchemaDefinition): GeneratedFile {
  const issues = validatePostgreSQLSchema(schema);
  if (issues.length > 0) throw new PostgreSQLGeneratorError(issues);

  const tables = [...schema.tables].sort((left, right) => left.name.localeCompare(right.name));
  const statements: string[] = [
    `-- Generated by Mavibase PostgreSQL generator.`,
    `-- Schema: ${schema.name}`,
    `-- Version: ${schema.version}`,
    "",
    ...tables.map(renderPostgreSQLTable),
  ];

  for (const table of tables) {
    for (const index of indexedColumns(table)) {
      const unique = index.unique ? "UNIQUE " : "";
      statements.push(
        `CREATE ${unique}INDEX ${quotePostgreSQLIdentifier(index.name)} ON ${quotePostgreSQLIdentifier(table.name)} (${index.columns.map(quotePostgreSQLIdentifier).join(", ")});`,
      );
    }
  }

  return {
    path: "database/schema.sql",
    content: `${statements.join("\n\n")}\n`,
  };
}
