import type {
  DatabaseSchemaDefinition,
  DatabaseSeedDefinition,
  DatabaseSeedTableDefinition,
} from "@mavibase/core";
import { defineDatabaseSeed } from "@mavibase/core";

import type { GeneratedFile } from "./index.js";
import { quotePostgreSQLIdentifier } from "./postgresql-generator.js";

export interface PostgreSQLSeedIssue {
  path: string;
  message: string;
}

export class PostgreSQLSeedGeneratorError extends Error {
  readonly code = "MAVIBASE_POSTGRESQL_SEED_GENERATOR_ERROR";
  readonly issues: readonly PostgreSQLSeedIssue[];

  constructor(issues: readonly PostgreSQLSeedIssue[]) {
    super(`Unable to generate PostgreSQL seeds: ${issues.map((issue) => issue.message).join(" ")}`);
    this.name = "PostgreSQLSeedGeneratorError";
    this.issues = issues;
  }
}

function sqlValue(value: unknown): string {
  if (value === null) return "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (typeof value === "number" && Number.isFinite(value)) return String(value);
  const serialized = typeof value === "string" ? value : JSON.stringify(value);
  return `'${String(serialized).replaceAll("'", "''")}'`;
}

function tableStatements(table: DatabaseSeedTableDefinition): string[] {
  const rows = table.rows;
  if (rows.length === 0) return [];
  const columns = [...new Set(rows.flatMap((row) => Object.keys(row)))].sort((left, right) =>
    left.localeCompare(right),
  );
  const values = rows
    .map((row) => `(${columns.map((column) => sqlValue(row[column])).join(", ")})`)
    .join(",\n  ");
  const mode = table.mode === "upsert" ? " ON CONFLICT DO NOTHING" : "";
  return [
    `INSERT INTO ${quotePostgreSQLIdentifier(table.table)} (${columns.map(quotePostgreSQLIdentifier).join(", ")}) VALUES\n  ${values}${mode};`,
  ];
}

function validateSeedTables(
  schema: DatabaseSchemaDefinition,
  seeds: readonly DatabaseSeedDefinition[],
): PostgreSQLSeedIssue[] {
  const issues: PostgreSQLSeedIssue[] = [];
  const tables = new Map(schema.tables.map((table) => [table.name, table]));
  for (const [seedIndex, seed] of seeds.entries()) {
    for (const [tableIndex, table] of seed.tables.entries()) {
      const schemaTable = tables.get(table.table);
      if (!schemaTable) {
        issues.push({
          path: `seeds[${seedIndex}].tables[${tableIndex}].table`,
          message: `Seed references unknown table: "${table.table}".`,
        });
        continue;
      }
      const columns = new Set(schemaTable.columns.map((column) => column.name));
      for (const [rowIndex, row] of table.rows.entries()) {
        for (const column of Object.keys(row)) {
          if (!columns.has(column)) {
            issues.push({
              path: `seeds[${seedIndex}].tables[${tableIndex}].rows[${rowIndex}].${column}`,
              message: `Seed references unknown column "${column}" on table "${table.table}".`,
            });
          }
        }
      }
    }
  }
  return issues;
}

export function generatePostgreSQLSeeds(
  schema: DatabaseSchemaDefinition,
  definitions: readonly DatabaseSeedDefinition[],
): GeneratedFile {
  const seeds = definitions
    .map(defineDatabaseSeed)
    .sort(
      (left, right) => (left.order ?? 0) - (right.order ?? 0) || left.id.localeCompare(right.id),
    );
  const issues = validateSeedTables(schema, seeds);
  if (issues.length > 0) throw new PostgreSQLSeedGeneratorError(issues);
  const statements = seeds.flatMap((seed) => [
    `-- Seed: ${seed.id} (${seed.name})`,
    ...seed.tables.flatMap(tableStatements),
  ]);
  return {
    path: "database/seeds.sql",
    content: `-- Generated by Mavibase PostgreSQL seed generator.\n\n${statements.length > 0 ? `${statements.join("\n\n")}\n` : ""}`,
  };
}
