import type {
  DatabaseColumnDefinition,
  DatabaseConstraintDefinition,
  DatabaseForeignKeyConstraint,
  DatabaseIndexDefinition,
  DatabaseTableDefinition,
} from "@mavibase/core";

import type { GeneratedFile } from "./index.js";
import {
  PostgreSQLGeneratorError,
  quotePostgreSQLIdentifier,
  renderPostgreSQLColumn,
  renderPostgreSQLConstraint,
  renderPostgreSQLTable,
} from "./postgresql-generator.js";

export type PostgreSQLAlterTableAction =
  | { type: "add-column"; column: DatabaseColumnDefinition }
  | { type: "drop-column"; column: string }
  | { type: "alter-column-type"; column: string; dataType: DatabaseColumnDefinition["type"] }
  | { type: "set-nullable"; column: string; nullable: boolean }
  | {
      type: "set-default";
      column: string;
      value: unknown;
      dataType: DatabaseColumnDefinition["type"];
    }
  | { type: "drop-default"; column: string };

export type PostgreSQLSqlOperation =
  | { type: "create-table"; table: DatabaseTableDefinition }
  | { type: "alter-table"; table: string; actions: readonly PostgreSQLAlterTableAction[] }
  | { type: "create-index"; table: string; index: DatabaseIndexDefinition }
  | { type: "add-foreign-key"; table: string; constraint: DatabaseForeignKeyConstraint }
  | { type: "add-constraint"; table: string; constraint: DatabaseConstraintDefinition };

const typeMap: Readonly<Record<DatabaseColumnDefinition["type"], string>> = {
  string: "TEXT",
  integer: "INTEGER",
  float: "DOUBLE PRECISION",
  decimal: "NUMERIC",
  boolean: "BOOLEAN",
  uuid: "UUID",
  datetime: "TIMESTAMPTZ",
  json: "JSONB",
};

function sqlLiteral(value: unknown, dataType: DatabaseColumnDefinition["type"]): string {
  if (value === null) return "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (typeof value === "number" && Number.isFinite(value)) return String(value);
  const literal = typeof value === "string" ? value : JSON.stringify(value);
  const escaped = String(literal).replaceAll("'", "''");
  return dataType === "json" ? `'${escaped}'::JSONB` : `'${escaped}'`;
}

function renderAlterAction(action: PostgreSQLAlterTableAction): string {
  if (action.type === "add-column") return `ADD COLUMN ${renderPostgreSQLColumn(action.column)}`;
  if (action.type === "drop-column")
    return `DROP COLUMN ${quotePostgreSQLIdentifier(action.column)}`;
  if (action.type === "alter-column-type") {
    return `ALTER COLUMN ${quotePostgreSQLIdentifier(action.column)} TYPE ${typeMap[action.dataType]}`;
  }
  if (action.type === "set-nullable") {
    return `ALTER COLUMN ${quotePostgreSQLIdentifier(action.column)} ${action.nullable ? "DROP NOT NULL" : "SET NOT NULL"}`;
  }
  if (action.type === "set-default") {
    return `ALTER COLUMN ${quotePostgreSQLIdentifier(action.column)} SET DEFAULT ${sqlLiteral(action.value, action.dataType)}`;
  }
  return `ALTER COLUMN ${quotePostgreSQLIdentifier(action.column)} DROP DEFAULT`;
}

function renderOperation(operation: PostgreSQLSqlOperation): string {
  if (operation.type === "create-table") return renderPostgreSQLTable(operation.table);
  if (operation.type === "alter-table") {
    return operation.actions
      .map(
        (action) =>
          `ALTER TABLE ${quotePostgreSQLIdentifier(operation.table)} ${renderAlterAction(action)};`,
      )
      .join("\n");
  }
  if (operation.type === "create-index") {
    return `CREATE ${operation.index.unique ? "UNIQUE " : ""}INDEX ${quotePostgreSQLIdentifier(operation.index.name)} ON ${quotePostgreSQLIdentifier(operation.table)} (${operation.index.columns.map(quotePostgreSQLIdentifier).join(", ")});`;
  }
  return `ALTER TABLE ${quotePostgreSQLIdentifier(operation.table)} ADD ${renderPostgreSQLConstraint(operation.constraint)};`;
}

function validateOperations(operations: readonly PostgreSQLSqlOperation[]): void {
  const issues = operations.flatMap((operation, index) => {
    if (operation.type === "create-table" && operation.table.name.trim().length === 0) {
      return [
        { path: `operations[${index}].table.name`, message: "Table name must not be empty." },
      ];
    }
    if (operation.type !== "create-table" && operation.table.trim().length === 0) {
      return [{ path: `operations[${index}].table`, message: "Table name must not be empty." }];
    }
    return [];
  });
  if (issues.length > 0) throw new PostgreSQLGeneratorError(issues);
}

export function generatePostgreSQLSql(
  operations: readonly PostgreSQLSqlOperation[],
): GeneratedFile {
  validateOperations(operations);
  return {
    path: "database/schema.sql",
    content: `-- Generated by Mavibase PostgreSQL SQL generator.\n\n${operations.map(renderOperation).join("\n\n")}\n`,
  };
}
